### ISSUE TITLE
Your xml submition

### ISSUE THREAD

**Issue by orthagh** [yild/gdprropa#1]
Hi.

I just received the proposal to add your plugin to https://plugins.glpi-project.org/
Before i accept it, please fix the logo and screenshots nodes of your xml.

The logo doesn't target a public url.
And the screenshots are github pages, you must use raw files:

![image](https://user-images.githubusercontent.com/418844/87515667-75092780-c67c-11ea-85b4-eaad1f3f3417.png)

Let me know here when corrections are done.

Regards

**Comment by yild** [comment]
xml updated, should I upload it again on https://plugins.glpi-project.org/

**Comment by orthagh** [comment]
no, no need, i will review it this afternoon

**Comment by orthagh** [comment]
Your plugin is validated and should appear in the plugin catalog soon (around 30min)
