### ISSUE TITLE
Create table error script

### ISSUE THREAD

**Issue by Cluster-X** [yild/gdprropa#4]
Hi,
i tried to install this plugin but when i select the option + in the plugin screen i receid the following error:

"Error during the database query: CREATE TABLE `glpi_plugin_gdprropa_configs` ( `id` int(11) NOT NULL auto_increment, `entities_id` int(11) NOT NULL default '0' COMMENT 'RELATION to glpi_entities (id)', `config` TEXT NOT NULL default '{}', `date_creation` datetime default NULL, `users_id_creator` int(11) default NULL COMMENT 'RELATION to glpi_users (id)', `date_mod` datetime default NULL, `users_id_lastupdater` int(11) default NULL COMMENT 'RELATION to glpi_users (id)', PRIMARY KEY (`id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci - Error is BLOB/TEXT column 'config' can't have a default value" 
If I fix the script and delete the text  "default '{}'" this work OK but I get another error in the next script.
So how can I resolve the problem? 

My configuration is:
CentOS 7
GLPI 9.4.5
Ver 15.1 Distrib 10.1.46-MariaDB
Server version: Apache/2.4.6 (CentOS)

Any help will be apprecited.
Thanks.

**Comment by yild** [comment]
This is related to yours mysql/mariadb configuration, whats the next error you get?

**Comment by Cluster-X** [comment]
that's the second error:

- Error during the database query: CREATE TABLE `glpi_plugin_gdprropa_records` ( `id` int(11) NOT NULL auto_increment, `entities_id` int(11) NOT NULL default '0' COMMENT 'RELATION to glpi_entities (id)', `is_recursive` tinyint(1) NOT NULL default '1', `is_deleted` tinyint(1) NOT NULL default '0', `name` varchar(255) collate utf8_unicode_ci default NULL, `content` varchar(1000) collate utf8_unicode_ci default NULL, `additional_info` varchar(1000) collate utf8_unicode_ci default NULL, `states_id` int(11) NOT NULL default '1' COMMENT 'RELATION to glpi_states (id)', `storage_medium` int(11) NOT NULL default '0' COMMENT 'Default status to UNDEFINED', `pia_required` tinyint(1) NOT NULL default '0', `pia_status` int(11) NOT NULL default '0' COMMENT 'Default status to UNDEFINED', `first_entry_date` datetime default NULL, `consent_required` tinyint(1) NOT NULL default '0', `consent_storage` varchar(1000) collate utf8_unicode_ci default NULL, `date_creation` datetime default NULL, `users_id_creator` int(11) default NULL COMMENT 'RELATION to glpi_users (id)', `date_mod` datetime default NULL, `users_id_lastupdater` int(11) default NULL COMMENT 'RELATION to glpi_users (id)', PRIMARY KEY (`id`), KEY `name` (`name`), KEY `status` (`status`), UNIQUE `un_per_record` (`name`, `entities_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci - Error is Key column 'status' doesn't exist in table

**Comment by yild** [comment]
check current version, second error should be fixed

**Comment by Cluster-X** [comment]
When i unzip the file on the plugin folder i cannot see in GLPI plugin page, to see it i must rename the plugin directory name from "gdprropa-master" to "gdpr" but with this version it doesn't work.... i continue to not see the plugin in the GLPI plugin screen.
I don't know what to do....

**Comment by pingax** [comment]
Hi, 

Navigate to the plugins' page and check `your-glpi`/files/_logs/php-errors.log

Edit: it seems it's because of your outdated GLPI. Latest stable release is 9.5.1. 

Try first to update your installation and try again activate the plugin.

**Comment by yild** [comment]
Plugin was developed with glpi 9.4.5, plugin checks if GLPI is at least 9.4.1. Also each plugin should display version requirements info in plugins list.

Post your /files/_logs/php-errors.log

**Comment by Cluster-X** [comment]
It work!!!! i must always rename the directory from gdprropa-1.0.1 to gdprropa but it work.

Thank you ;)
